spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 50
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

server:
  forward-headers-strategy: framework

logging:
  level:
    org:
      hibernate: info
      springframework: debug
