spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
        create_empty_composites:
          enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  forward-headers-strategy: framework
  tomcat:
    max-http-form-post-size: 25MB

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLE}

management:
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, prometheus
      base-path: ${ACTUATOR_BASE_PATH}
  metrics:
    tags:
      application: ${ACTUATOR_APP_TAG}
  server:
    port: ${ACTUATOR_SERVER_PORT}

openapi:
  dev_url: ${OPENAPI_DEV_URL}

jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_expire_time: ${JWT_ACCESS_EXPIRE_TIME}
  refresh_expire_time: ${JWT_REFRESH_EXPIRE_TIME}

oauth:
  apple:
    iss: https://appleid.apple.com
    client_id: ${OAUTH_APPLE_CLIENT_ID}
    nonce: ${OAUTH_APPLE_NONCE}

file:
  dir: ${FILE_PATH}

monitor:
  pattern: ${MONITOR_PATTERN}
  user: ${MONITOR_USER}
  password: ${MONITOR_PASSWORD}
  role: ${MONITOR_ROLE}
