version: "3.8"

services:
  db:
    image: ${DB_IMAGE}
    container_name: foodbowl_db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0.12
    container_name: foodbowl_redis
    ports:
      - "6379:6379"
