version: "3.8"

services:
  source:
    image: foodbowl-db
    container_name: foodbowl-source
    ports:
      - 3306:3306
    env_file:
      - .env.source
    volumes:
      - ./mysql-source.cnf:/etc/mysql/conf.d/mysql.cnf
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  replica:
    image: foodbowl-db
    container_name: foodbowl-replica
    ports:
      - 3307:3306
    env_file:
      - .env.replica
    volumes:
      - ./mysql-replica.cnf:/etc/mysql/conf.d/mysql.cnf
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0.12
    container_name: foodbowl-redis
    ports:
      - 6379:6379
