version: "3.8"

services:
  db:
    image: ${DB_IMAGE}
    container_name: foodbowl-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0.12
    container_name: foodbowl-redis
    ports:
      - "6379:6379"
